name: real_time_analytics
version: 1.0
profile: real_time_analytics 

# Corrected folder paths
model-paths: ["dbt_models"]      
seed-paths: ["data"]             
analysis-paths: ["analysis"]
test-paths: ["tests"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Models configuration
models:
  real_time_analytics:
    +materialized: view 

